debug: false # ??? ?? ??
management.endpoints.web.exposure.include: "*" # ?? ? ????? ??

logging:
  level:
    com.example.back: debug # ?? ???? ???? ??? ??? ??? ??
    org.springframework.web.servlet: debug # response, request ??? ??? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace #sql? ????? ??? ??

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/mydb # jdbc ??
#    username: root
#    password: dbdnjs12!@
#    driver-class-name: com.mysql.cj.jdbc.Driver # jdbc ???? ??
      url: jdbc:h2:mem:testdb
      username: sa
      driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create # entity? ?? ???? ??? ??
    show-sql: true # sql ?? ???? ??
    properties:
      hibernate:
        format_sql: true # ? ?? ??? ???? ????? ??? ??
        default_batch_fetch_size: 100 # fetch_size ?? n+1 ?????
  h2:
    console:
      enabled: true
      path: /h2-console




